In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [32]:
from sklearn.datasets import load_breast_cancer,make_classification
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split


In [33]:
dataset=load_breast_cancer()
X=dataset.data
y=dataset.target
feature=dataset.feature_names

In [34]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.25,
    stratify=y

)

In [35]:
model_gussian=GaussianNB()
model_gussian.fit(X_train,y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09


In [36]:
y_pred=model_gussian.predict(X_test)
(y_pred)

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1])

In [37]:
acc=accuracy_score(y_test,y_pred)
(acc)

0.9090909090909091

Multinominal naviebayes algorithm that are used for text?count data

In [38]:
text=[
    "buy a cheap medicince",
    "win a free prize and you won a lottery",
    "scheduled a meeting tomorrow",
    "project deadline tomorrow",
    "offer letter accepted and confirmed",
    "limited time offer",
    "let discuss the report"
]
labels=[0,0,1,1,1,1,1]
vectorizer=CountVectorizer()
X_texts=vectorizer.fit_transform(text)

X_tr,X_txt,y_tr,y_txt=train_test_split(
    X_texts,labels,test_size=0.33,random_state=42
)
multi_model=MultinomialNB()
multi_model.fit(X_tr,y_tr)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [39]:
y_pred=multi_model.predict(X_txt)
(y_pred)

array([1, 1, 1])

In [40]:
print("the accuracy _score is:",accuracy_score(y_txt,y_pred))

the accuracy _score is: 0.3333333333333333


bernoulli model

In [42]:
X,y=make_classification(
    n_samples=200,
    n_features=10,
    n_informative=5,
    n_redundant=0,
    random_state=42
)

In [43]:
X=(X>0).astype(int)

In [44]:
X_tr,X_txt,y_tr,y_txt=train_test_split(
    X,y,test_size=0.33,random_state=42
)
b_model=BernoulliNB()
b_model.fit(X_tr,y_tr)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"binarize binarize: float or None, default=0.0Threshold for binarizing (mapping to booleans) of sample features.If None, input is presumed to already consist of binary vectors.",0.0
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [45]:
y_pred=b_model.predict(X_txt)
(y_pred)

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1])

In [46]:
acc=accuracy_score(y_pred,y_txt)
(acc)

0.6060606060606061